updated contributing.md
Ibadan-Techies/badtechies pull request #116
Opened 2023-07-06 15:51 UTC by adekunbee

closes #115

2023-07-06 16:12 UTC, WojuadeAA approved these changes
Nice job

2023-07-08 05:33 UTC, kelvinsekx requested changes
To ensure consistency everywhere on this file, 
- you should use a similar symbol `-` to indicate every terminal prompt. For example, you were using 
```bash
-npm install
-npm run dev
```
This pattern should be used on every terminal instruction existing on the file

- Another addition, instead of using `-` to indicate terminal prompts, I would have prefered `$: `. This way it doesn't confuse or conflict with other terminal instructions like `-m`. The dollar sign is very common with terminal prompts.

2023-07-10 13:19 UTC, kelvinsekx requested changes
Take line 17 for example where we didn't show any sign it is a terminal prompt, can you put the dollar symbol so the reader knows it is a terminal prompt. Do this every part of the file that is supposed to be a start of prompt.

Also I realized you didn't change everywhere - was used for example line 38, 39 and so on

2023-07-10 15:44 UTC, kelvinsekx approved these changes

2023-07-10 15:45 UTC, merged